name: pneumonie
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - pillow
  - tqdm
  - jupyterlab
  - ipywidgets
  - pip
  - pip:
    - tensorflow
    - opencv-python